/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe de base de datos
         * @description Comprueba la conexión a PostgreSQL y que la extensión pgvector está habilitada.
         */
        get: operations["health_db_api_v1_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DatabaseHealthResponse */
        DatabaseHealthResponse: {
            /** Status */
            status: string;
            /** Pgvector Version */
            pgvector_version: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @description Identificador estable del error, p. ej. 'not_found'.
             */
            code: string;
            /**
             * Message
             * @description Descripción legible del error.
             */
            message: string;
            /**
             * Request Id
             * @description Identificador de la solicitud (cabecera X-Request-ID).
             */
            request_id?: string | null;
            /**
             * Details
             * @description Detalle por campo; presente en errores de validación.
             */
            details?: components["schemas"]["ErrorDetail"][] | null;
        };
        /**
         * ErrorDetail
         * @description Un problema concreto, normalmente asociado a un campo de la solicitud.
         */
        ErrorDetail: {
            /**
             * Loc
             * @description Ubicación del problema, p. ej. ['body', 'email'].
             */
            loc: (string | number)[];
            /** Message */
            message: string;
            /**
             * Type
             * @description Tipo de error de validación.
             */
            type: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Los datos enviados no son válidos. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error interno del servidor. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_db_api_v1_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseHealthResponse"];
                };
            };
            /** @description Los datos enviados no son válidos. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error interno del servidor. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Servicio no disponible. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
